"""
ai_layer/main.py
──────────────────────────────────────────────────────────────────────────────
FastAPI application – AI Insights Service

Endpoints:
  GET  /health              → liveness check
  GET  /insights/latest     → returns the last generated insights (in-memory)
  POST /insights/generate   → reads mart data, calls OpenAI, stores + returns

Swagger UI: http://localhost:8001/docs
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Any

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

from services.data_reader import read_mart_data
from services.insight_generator import generate_insights

# ─── Logging ─────────────────────────────────────────────────────────────────
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# ─── App ─────────────────────────────────────────────────────────────────────
app = FastAPI(
    title="AI Data Pipeline Lab – Insights Service",
    description=(
        "Reads dbt mart tables from the trading database and uses "
        "OpenAI GPT-4o-mini to generate daily trading insights."
    ),
    version="1.0.0",
)

# ─── In-memory store (last generated insights) ───────────────────────────────
_latest_insights: dict[str, Any] | None = None


# ─── Schemas ─────────────────────────────────────────────────────────────────
class GenerateRequest(BaseModel):
    execution_date: str | None = None


class InsightsResponse(BaseModel):
    anomaly_summary: str
    risk_explanation: str
    operational_insight: str
    model: str
    generated_at: str
    execution_date: str | None = None
    prompt_tokens: int | None = None
    completion_tokens: int | None = None


# ─── Routes ──────────────────────────────────────────────────────────────────
@app.get("/health", tags=["ops"])
def health() -> dict[str, str]:
    return {"status": "ok", "timestamp": datetime.now(timezone.utc).isoformat()}


@app.get("/insights/latest", response_model=InsightsResponse, tags=["insights"])
def get_latest_insights() -> dict[str, Any]:
    """Returns the last insights generated by /insights/generate."""
    if _latest_insights is None:
        raise HTTPException(
            status_code=404,
            detail="No insights generated yet. Call POST /insights/generate first.",
        )
    return _latest_insights


@app.post("/insights/generate", response_model=InsightsResponse, tags=["insights"])
def generate(request: GenerateRequest) -> dict[str, Any]:
    """
    Reads mart data from PostgreSQL and calls OpenAI to produce insights.
    Result is cached in memory for GET /insights/latest.
    """
    global _latest_insights  # noqa: PLW0603

    logger.info("Reading mart data from PostgreSQL…")
    mart_data = read_mart_data()

    if mart_data.get("error"):
        raise HTTPException(
            status_code=503,
            detail=f"Database unavailable: {mart_data['error']}",
        )

    if not mart_data["customer_activity"] and not mart_data["risk_signals"]:
        raise HTTPException(
            status_code=422,
            detail=(
                "Mart tables are empty or do not exist. "
                "Run the Airflow pipeline first (make trigger-dag)."
            ),
        )

    logger.info("Calling insight generator…")
    insights = generate_insights(mart_data)
    insights["execution_date"] = request.execution_date

    _latest_insights = insights
    return insights


@app.get("/data/summary", tags=["data"])
def data_summary() -> dict[str, Any]:
    """Returns raw mart data for inspection (no AI call)."""
    return read_mart_data()
